"""Shared risk factor identifiers."""

from __future__ import annotations

RISK_YIELD_CURVE = "yield_curve"
RISK_DISCOUNT_CURVE = "discount_curve"
RISK_FLOAT_INDEX = "float_index"
RISK_OVERNIGHT_INDEX = "overnight_index"
RISK_RATE_VOL = "rate_vol"
RISK_FX_SPOT = "fx_spot"
RISK_INTEREST_RATE_DIFFERENTIAL = "interest_rate_differential"
RISK_FX_VOL = "fx_vol"
RISK_EQUITY_SPOT = "equity_spot"
RISK_DIVIDEND_YIELD = "dividend_yield"
RISK_INTEREST_RATE = "interest_rate"
RISK_EQUITY_VOL = "equity_vol"
RISK_CREDIT_SPREAD = "credit_spread"
RISK_DEFAULT_INTENSITY = "default_intensity"
RISK_RECOVERY_RATE = "recovery_rate"
RISK_CREDIT_VOL = "credit_vol"
RISK_ASSET_SPOT = "asset_spot"
RISK_FUNDING_RATE = "funding_rate"
RISK_COMMODITY_SPOT = "commodity_spot"
RISK_CONVENIENCE_YIELD = "convenience_yield"
RISK_COMMODITY_VOL = "commodity_vol"
RISK_MULTI_ASSET_SPOTS = "multi_asset_spots"
RISK_CORRELATION = "correlation"
RISK_MULTI_ASSET_VOL = "multi_asset_vol"
RISK_UNDERLYING_SPOT = "underlying_spot"
RISK_FX_RATE = "fx_rate"
RISK_UNDERLYING_VOL = "underlying_vol"

ALL_RISK_FACTORS = (
    RISK_YIELD_CURVE,
    RISK_DISCOUNT_CURVE,
    RISK_FLOAT_INDEX,
    RISK_OVERNIGHT_INDEX,
    RISK_RATE_VOL,
    RISK_FX_SPOT,
    RISK_INTEREST_RATE_DIFFERENTIAL,
    RISK_FX_VOL,
    RISK_EQUITY_SPOT,
    RISK_DIVIDEND_YIELD,
    RISK_INTEREST_RATE,
    RISK_EQUITY_VOL,
    RISK_CREDIT_SPREAD,
    RISK_DEFAULT_INTENSITY,
    RISK_RECOVERY_RATE,
    RISK_CREDIT_VOL,
    RISK_ASSET_SPOT,
    RISK_FUNDING_RATE,
    RISK_COMMODITY_SPOT,
    RISK_CONVENIENCE_YIELD,
    RISK_COMMODITY_VOL,
    RISK_MULTI_ASSET_SPOTS,
    RISK_CORRELATION,
    RISK_MULTI_ASSET_VOL,
    RISK_UNDERLYING_SPOT,
    RISK_FX_RATE,
    RISK_UNDERLYING_VOL,
)

__all__ = [
    "RISK_YIELD_CURVE",
    "RISK_DISCOUNT_CURVE",
    "RISK_FLOAT_INDEX",
    "RISK_OVERNIGHT_INDEX",
    "RISK_RATE_VOL",
    "RISK_FX_SPOT",
    "RISK_INTEREST_RATE_DIFFERENTIAL",
    "RISK_FX_VOL",
    "RISK_EQUITY_SPOT",
    "RISK_DIVIDEND_YIELD",
    "RISK_INTEREST_RATE",
    "RISK_EQUITY_VOL",
    "RISK_CREDIT_SPREAD",
    "RISK_DEFAULT_INTENSITY",
    "RISK_RECOVERY_RATE",
    "RISK_CREDIT_VOL",
    "RISK_ASSET_SPOT",
    "RISK_FUNDING_RATE",
    "RISK_COMMODITY_SPOT",
    "RISK_CONVENIENCE_YIELD",
    "RISK_COMMODITY_VOL",
    "RISK_MULTI_ASSET_SPOTS",
    "RISK_CORRELATION",
    "RISK_MULTI_ASSET_VOL",
    "RISK_UNDERLYING_SPOT",
    "RISK_FX_RATE",
    "RISK_UNDERLYING_VOL",
    "ALL_RISK_FACTORS",
]
